table Dim_Date
	lineageTag: d1a2b3c4-d5e6-7890-d1a2-b3c4d5e67890

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: d1000001-0000-0000-0000-000000000001
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 4693e5cc-54ca-43fe-b90a-965747ae3eab
			defaultHierarchy: LocalDateTable_34e9a8e6-dcc0-494d-b196-0a583bdb23cc.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: d1000002-0000-0000-0000-000000000002
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: d1000003-0000-0000-0000-000000000003
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: d1000004-0000-0000-0000-000000000004
		summarizeBy: none
		sourceColumn: MonthName

	column Quarter
		dataType: int64
		formatString: 0
		lineageTag: d1000006-0000-0000-0000-000000000006
		summarizeBy: sum
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column WeekDay
		dataType: int64
		formatString: 0
		lineageTag: d1000008-0000-0000-0000-000000000008
		summarizeBy: sum
		sourceColumn: WeekDay

		annotation SummarizationSetBy = Automatic

	column WeekNum
		dataType: int64
		formatString: 0
		lineageTag: d1000010-0000-0000-0000-000000000010
		summarizeBy: sum
		sourceColumn: WeekNum

		annotation SummarizationSetBy = Automatic

	partition Dim_Date = m
		mode: import
		source =
				let
					StartDate = #date(2024, 1, 1),
					EndDate = #date(2027, 12, 31),
					DayCount = Duration.Days(EndDate - StartDate) + 1,
					DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
					TableFromList = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
					ChangedType = Table.TransformColumnTypes(TableFromList, {{"Date", type date}}),
					AddYear = Table.AddColumn(ChangedType, "Year", each Date.Year([Date]), Int64.Type),
					AddMonth = Table.AddColumn(AddYear, "Month", each Date.Month([Date]), Int64.Type),
					AddMonthName = Table.AddColumn(AddMonth, "MonthName", each Date.MonthName([Date]), type text),
					AddQuarter = Table.AddColumn(AddMonthName, "Quarter", each Date.QuarterOfYear([Date]), Int64.Type),
					AddWeekDay = Table.AddColumn(AddQuarter, "WeekDay", each Date.DayOfWeek([Date]), Int64.Type),
					AddWeekNum = Table.AddColumn(AddWeekDay, "WeekNum", each Date.WeekOfYear([Date]), Int64.Type)
				in
					AddWeekNum

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

