table Languages
	lineageTag: l1a2b3c4-d5e6-7890-l1a2-b3c4d5e67890

	column language
		dataType: string
		isKey
		lineageTag: l1000001-0000-0000-0000-000000000001
		summarizeBy: none
		sourceColumn: language

		annotation SummarizationSetBy = Automatic

	column display_name
		dataType: string
		lineageTag: l1000002-0000-0000-0000-000000000002
		summarizeBy: none
		sourceColumn: display_name

		annotation SummarizationSetBy = Automatic

	column linter
		dataType: string
		lineageTag: l1000003-0000-0000-0000-000000000003
		summarizeBy: none
		sourceColumn: linter

		annotation SummarizationSetBy = Automatic

	column coverage_tool
		dataType: string
		lineageTag: l1000004-0000-0000-0000-000000000004
		summarizeBy: none
		sourceColumn: coverage_tool

		annotation SummarizationSetBy = Automatic

	partition Languages = m
		mode: import
		source =
				let
					StorageUrl = "https://" & StorageAccountName & ".dfs.core.windows.net/" & ContainerName,
					Source = AzureStorage.DataLake(StorageUrl),
					FilteredRows = Table.SelectRows(Source, each [Name] = "languages.json" and Text.Contains([Folder Path], "metadata")),
					ParsedContent = Table.AddColumn(FilteredRows, "ParsedJson", each let p = Json.Document([Content]) in if p is list then p else {p}),
					ExpandedRows = Table.ExpandListColumn(ParsedContent, "ParsedJson"),
					ExpandedCols = Table.ExpandRecordColumn(ExpandedRows, "ParsedJson", {"language", "display_name", "linter", "coverage_tool"}),
					SelectedCols = Table.SelectColumns(ExpandedCols, {"language", "display_name", "linter", "coverage_tool"})
				in
					SelectedCols

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

