table Repositories
	lineageTag: r1a2b3c4-d5e6-7890-r1a2-b3c4d5e67890

	column repo_name
		dataType: string
		isKey
		lineageTag: r1000001-0000-0000-0000-000000000001
		summarizeBy: none
		sourceColumn: repo_name

		annotation SummarizationSetBy = Automatic

	column org
		dataType: string
		lineageTag: r1000002-0000-0000-0000-000000000002
		summarizeBy: none
		sourceColumn: org

		annotation SummarizationSetBy = Automatic

	column url
		dataType: string
		lineageTag: r1000003-0000-0000-0000-000000000003
		dataCategory: WebUrl
		summarizeBy: none
		sourceColumn: url

		annotation SummarizationSetBy = Automatic

	column scan_domain
		dataType: string
		lineageTag: r1000004-0000-0000-0000-000000000004
		summarizeBy: none
		sourceColumn: scan_domain

		annotation SummarizationSetBy = Automatic

	partition Repositories = m
		mode: import
		source =
				let
					StorageUrl = "https://" & StorageAccountName & ".dfs.core.windows.net/" & ContainerName,
					Source = AzureStorage.DataLake(StorageUrl),
					FilteredRows = Table.SelectRows(Source, each [Name] = "repositories.json" and Text.Contains([Folder Path], "metadata")),
					ParsedContent = Table.AddColumn(FilteredRows, "ParsedJson", each let p = Json.Document([Content]) in if p is list then p else {p}),
					ExpandedRows = Table.ExpandListColumn(ParsedContent, "ParsedJson"),
					ExpandedCols = Table.ExpandRecordColumn(ExpandedRows, "ParsedJson", {"repo_name", "org", "url", "scan_domain"}),
					SelectedCols = Table.SelectColumns(ExpandedCols, {"repo_name", "org", "url", "scan_domain"})
				in
					SelectedCols

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

