table ScanTools
	lineageTag: s1a2b3c4-d5e6-7890-s1a2-b3c4d5e67890

	column tool_name
		dataType: string
		isKey
		lineageTag: s1000001-0000-0000-0000-000000000001
		summarizeBy: none
		sourceColumn: tool_name

		annotation SummarizationSetBy = Automatic

	column display_name
		dataType: string
		lineageTag: s1000002-0000-0000-0000-000000000002
		summarizeBy: none
		sourceColumn: display_name

		annotation SummarizationSetBy = Automatic

	column version
		dataType: string
		lineageTag: s1000003-0000-0000-0000-000000000003
		summarizeBy: none
		sourceColumn: version

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: s1000004-0000-0000-0000-000000000004
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	partition ScanTools = m
		mode: import
		source =
				let
					StorageUrl = "https://" & StorageAccountName & ".dfs.core.windows.net/" & ContainerName,
					Source = AzureStorage.DataLake(StorageUrl),
					FilteredRows = Table.SelectRows(Source, each [Name] = "scan-tools.json" and Text.Contains([Folder Path], "metadata")),
					ParsedContent = Table.AddColumn(FilteredRows, "ParsedJson", each let p = Json.Document([Content]) in if p is list then p else {p}),
					ExpandedRows = Table.ExpandListColumn(ParsedContent, "ParsedJson"),
					ExpandedCols = Table.ExpandRecordColumn(ExpandedRows, "ParsedJson", {"tool_name", "display_name", "version", "category"}),
					SelectedCols = Table.SelectColumns(ExpandedCols, {"tool_name", "display_name", "version", "category"})
				in
					SelectedCols

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

